[
  {
    "value": "Generate a cube with 30 cm sides",
    "id": 1,
    "lbl": [
      {
        "start": 11,
        "end": 15,
        "text": "cube",
        "labels": [
          "Shape"
        ]
      },
      {
        "start": 24,
        "end": 26,
        "text": "cm",
        "labels": [
          "Unit"
        ]
      },
      {
        "start": 21,
        "end": 23,
        "text": "30",
        "labels": [
          "Dimension"
        ]
      }
    ],
    "annotator": 1,
    "annotation_id": 1,
    "created_at": "2025-06-10T17:46:07.539816Z",
    "updated_at": "2025-06-10T17:46:07.539831Z",
    "lead_time": 23.003
  },
  {
    "value": "Generate a spur gear with 13 teeth",
    "id": 2,
    "lbl": [
      {
        "start": 26,
        "end": 28,
        "text": "13",
        "labels": [
          "ShapeSubType"
        ]
      },
      {
        "start": 16,
        "end": 20,
        "text": "gear",
        "labels": [
          "Shape"
        ]
      },
      {
        "start": 11,
        "end": 15,
        "text": "spur",
        "labels": [
          "ShapeSubType"
        ]
      },
      {
        "start": 29,
        "end": 34,
        "text": "teeth",
        "labels": [
          "Unit"
        ]
      }
    ],
    "annotator": 1,
    "annotation_id": 2,
    "created_at": "2025-06-10T17:47:34.715793Z",
    "updated_at": "2025-06-10T17:47:34.715805Z",
    "lead_time": 84.703
  }
]